import classNames from 'classnames';
import { Inter } from 'next/font/google';
import { redirect } from 'next/navigation';
import { Toaster } from 'react-hot-toast';
import getUser from '../api/get_user';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ManCom: Your daily driver',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const { user = {} } = await getUser();

  if (user.id) {
    redirect('/dashboard');
  }

  return (
    <html lang='en'>
      <body
        className={classNames(
          inter.className,
          'bg-purple-600',
          'relative h-screen',
          'flex flex-col'
        )}
      >
        <Toaster position='top-center' />
        {children}
      </body>
    </html>
  );
}
