import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import classNames from 'classnames';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ManCom: Your daily driver',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={classNames(
          inter.className,
          'bg-purple-600',
          'relative h-screen',
          'flex flex-col'
        )}
      >
        <Toaster position='top-center' />
        {children}
      </body>
    </html>
  );
}
