import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import classNames from "classnames";
import Footer from "./common_components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ManCom: Your daily driver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, "bg-purple-950", "h-screen relative", "flex flex-col")}>
        <Toaster position="top-center" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
