import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import classNames from "classnames";
import Footer from "./common_components/footer";
import TopBar from "./common_components/top_bar";
import getUser from "./api/get_user";
import { redirect } from "next/dist/server/api-utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ManCom: Your daily driver",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let user = await getUser() || {};

  if(user?.id){
    redirect("/dashboard");
  }

  return (
    <html lang="en">
      <body className={classNames(inter.className, "bg-purple-600", "h-screen relative", "flex flex-col")}>
        <Toaster position="top-center" />
        <TopBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
