import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import classNames from "classnames";
import Footer from "@/CommonComponents/Footer";
import TopBar from "@/CommonComponents/TopBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ManCom: Your daily driver",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, "bg-purple-600", "flex flex-col", "min-h-screen")}>
        <Toaster position="top-center" />
        <TopBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
